version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: calendar-app-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passwordb
      POSTGRES_DB: calendar_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - calendar-network

volumes:
  postgres_data:

networks:
  calendar-network:
